//tested on ae20-25
//source code availabe upon request: @mouffinmix on disc
var  read_me = "developed by muffinmix :3"


    /* =====================================
                    place file in [Scipt UI Panels] folder
                                typically found at :
    C:\Program Files\Adobe\Adobe After Effects 20XX\Support Files\Scripts\ScriptUI Panels 
    ========================================= */

    /* ============================
          Button Functionality
    ============================== 
ADJ: 
            CLICK creates trimmed adjustment layers for each layer selected
            ALT-CLICK creates 1 adjustment layer from the first to last layer selected
            if no layer is selected, creates adj layer spanning the full comp duration

NULL: 
            CLICK creates a trimmed null autoparented to selected layers
            ALT-CLICK auto adds POS and SCALE keyframes  
            if no layer is selected, creates null spanning the full comp duration

TEXT: 
            CLICK creates a trimmed text layer for each layer you have selected. 
            if no layer is selected, creates text spanning the full comp duration
            
SOLID: 
            CLICK creates a black solid trimmed to first selected layers
            ALT-CLICK lets you select the solid color beforehand
            if no layer is selected, creates solid spanning the full comp duration

ƒ: 
            CLICK creates "one framers" at the location of your Current Time Indicator (CTI) / playhead
            -the amount is based on the number selected from the drop down menu on the right
    
rename: 
            renames adjustment layers to the effects applied
            *MADE BY kaim, with some adjustmentsa by me
            
*/

// custom renames 

    var nicknames = {
        "Motion Tile": "MT",
        "Gaussian Blur": "GB",
        "Glow": "G",
        "Tint": "T",
        "Curves": "C"
        // Add more as needed
    };

    // Define exclusions (effect names to ignore completely)
    var exclusions = [
        "CC RepeTile",
        "Slider Control",
        "Point Control"
        // Add more as needed
    ];

// dont touch =^w^=
eval("@JSXBIN@ES@2.0@MyBbyBn0AGJBnASzEjDjPjOjWByBARFFdyBFdAFdBFdCFdDfnftJCnASzCjYhRCyB\
 ndDftJDnASzIjBjEjKiDjPjVjOjUDyBndBftJEnASzRjQjJjDjLjFjEiDjPjMjPjSiHjMjPjCjBjMEy\
 BnbftOGbyHn0ABJHnASzHjSjFjBjEifjNjFFyBneAftACzChdhdGVFfyBnnbnJ2mCCnAENyBnAMJbyB\
 nADMLbyBnALMmJbyBn0AWOmKbymLn0ABJmLnASzKjTjUjBjSjUiWjBjMjVjFHKARDFdBFdBFdBfnffA\
 UzCjcjcIhzBhBJVHfKCzChBhdKXzGjMjFjOjHjUjILfVHfKnndDnnnJmOnASzEjDjPjNjQMAXzKjBjD\
 jUjJjWjFiJjUjFjNNfXzHjQjSjPjKjFjDjUOfjzDjBjQjQPfnftOmPbmQn0ACJmQnAEjzFjBjMjFjSj\
 UQfRBFeTiOjPhAjDjPjNjQhAjJjThAjTjFjMjFjDjUjFjEffZmRnAFbAUIhJVMfAhJCzKjJjOjTjUjB\
 jOjDjFjPjGRVMfAjzIiDjPjNjQiJjUjFjNSfnnnnnJmUnASzOjTjFjMjFjDjUjFjEiMjBjZjFjSjTTB\
 AnnftamVbymWn0ABOmWJmWnAEXzEjQjVjTjIUfVTfBRBVzBjJVfCffAXzIjTjFjMjFjDjUjFjEWfEXz\
 FjMjBjZjFjSXfVMfARBVVfCffnAVVfCBXzJjOjVjNiMjBjZjFjSjTYfVMfAByBzChchdZJmanASzHjO\
 jFjXiOjVjMjMgaDEXzHjBjEjEiOjVjMjMgbfXzGjMjBjZjFjSjTgcfVMfAnfnftJmbnASzPjOjFjXiD\
 jPjMjPjSiDjPjOjUjSjPjMgdEEXzLjBjEjEiQjSjPjQjFjSjUjZgefEXzIjQjSjPjQjFjSjUjZgffVg\
 afDRBFeSiBiEiCiFhAiFjGjGjFjDjUhAiQjBjSjBjEjFffRBFeSiBiEiCiFhAiDjPjMjPjShAiDjPjO\
 jUjSjPjMffnftJmcnASzMjUjIjFiDjPjMjPjSiQjSjPjQhAFEXgffVgdfERBFeXiBiEiCiFhAiDjPjM\
 jPjShAiDjPjOjUjSjPjMhNhQhQhQhRffnftJmfnASzQjPjSjJjHiTjIjZiDjPjOjEjJjUjJjPjOhBGX\
 zNjIjJjEjFiTjIjZiMjBjZjFjSjThCfVMfAnftOnAJnAnABXhCfVMfAnctfACGVhBfGnncfnJnBnABX\
 zDjTjIjZhDfVgafDnctfJnCnABXzHjFjOjBjCjMjFjEhEfVgafDncffJnFnAEXzIjTjFjUiWjBjMjVj\
 FhFfVhAfFRBVHfKffJnInASzLjFjEjJjUiWjBjMjVjFiJiEhGHnd2mAIftJnJnABXWfVhAfFnctfJnK\
 nAEXzOjFjYjFjDjVjUjFiDjPjNjNjBjOjEhHfjPfRBVhGfHffJnNnASzGjSjFjTjVjMjUhIIXzFjWjB\
 jMjVjFhJfVhAfFnftOnQbynRn0ABJnRnAEXzGjSjFjNjPjWjFhKfVgafDnfAVgafDnJnVnABXhCfVMf\
 AVhBfGnfanYbynZn0ABJnZnABXWfEXXfVMfARBQzAhLfVTfBVVfCffnctfAVVfCAXLfVTfBByBzBhch\
 MJndnASzPjTjUjBjSjUiWjBjMjVjFiJjOiSjHjChNJARDXzBhQhOfVHfKXzBhRhPfVHfKXzBhShQfVH\
 fKfnftZnenAdCGEXzIjUjPiTjUjSjJjOjHhRfVhIfInfEXhRfVhNfJnfnnFbVhIfIALhN4J0AiAV4C0\
 AiAH40BhAga4D0AiAgd4E0AiAhA4F0AiAhG4H0AiAM40BiAhB4G0AiAT4B0AiAhI4I0AiABKAzXiHjP\
 jPjEiCjPjZiOjJjOjKjBiDjPjMjPjSiQjJjDjLjFjShSAnfM2BBbyBn0ADJ2CBnASzDjOjVjNhTAXhO\
 fVzFjBjSjSjBjZhUfCnftO2DBby2FBn0ABa2FBby2GBn0ABO2GBby2HBn0ABJ2HBnAShTAQhLfVhUfC\
 VVfBnffAChMQhLfVhUfCVVfBVhTfAnnnAVVfBBXLfVhUfCByBhMAVzBjChVfDby2NBn0ABa2NBby2OB\
 n0ABO2OBby2PBn0ABJ2PBnAShTAQhLfVhUfCVVfBnffACzBhehWQhLfVhUfCVVfBVhTfAnnnAVVfBBX\
 LfVhUfCByBhMZ2TBnAVhTf0AEV4B0AiAhT40BiAhV4B0AhAhU40BhACCAzGjNjJjOjNjBjYhXA2UBM2\
 WBbyBn0AGJ2XBnAEXzOjCjFjHjJjOiVjOjEjPiHjSjPjVjQhYfjPfRBFeUiOjFjXhAiBjEjKjVjTjUj\
 NjFjOjUhAiMjBjZjFjSffJ2YBnASMAXNfXOfjPfnftJ2ZBnASzRjTjFjMjFjDjUjFjEiMjBjZjFjSjT\
 iBjSjShZBXTfVMfAnftJ2gaBnASzLjOjVjNiTjFjMjFjDjUjFjEhaCXLfXTfVMfAnftO2gcBb2geBn0\
 AFJ2geBnASzFjJjOiQjUjThbDEjzFiBjSjSjBjZhcfntnftJ2gfBnASzGjPjVjUiQjUjThdEEjhcfnt\
 nftJ2hABnASzDjJjOjEheFEjhcfntnfta2hDBb2hEBn0ADJ2hEBnAEXUfVhbfDRBXzHjJjOiQjPjJjO\
 jUhffQhLfVhZfBVzBjKiAfGffJ2hFBnAEXUfVhdfERBXzIjPjVjUiQjPjJjOjUiBfQhLfVhZfBViAfG\
 ffJ2hGBnAEXUfVhefFRBXzFjJjOjEjFjYiCfQhLfVhZfBViAfGffAViAfGAVhafCByBhMO2hKBb2hMB\
 n0ANJ2hMBnASzDiNiJiOiDHEjhXfRCVhbfDFdBffnftJ2hNBnASzDiNiBiYiEIEjhXfRCVhdfEFdAff\
 nftJ2hOBnASzFjNjJjOjJjOiFJEjhXfRCVhefFFdBffnftJ2hPBnASzMjGjJjSjTjUiJjOiQjPjJjOj\
 UiGKViDfHnftJ2hQBnASzMjMjBjTjUiPjVjUiQjPjJjOjUiHLViEfInftJ2hSBnASzBjTiIMXzEjOjB\
 jNjFiJfXhOfVhZfBnftO2hTBby2hUBn0ABJ2hUBnASiIMEXzJjTjVjCjTjUjSjJjOjHiKfXiJfXhOfV\
 hZfBRCFdJFdRffnffACGEXiKfViIfMRCFdAFdIffnneHjBjEjKhAjGjPjSby2hXBn0ABJ2hXBnASiIM\
 EXiKfXiJfXhOfVhZfBRCFdAFdIffnffJ2hbBnASzIjBjEjKiMjBjZjFjSiLNEXzIjBjEjEiTjPjMjJj\
 EiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffCzBh\
 LiNnViIfMeIjBjEjKhAjGjPjShAnXzFjXjJjEjUjIiOfVMfAXzGjIjFjJjHjIjUiPfVMfAFdBFdBffn\
 ftJ2hcBnABXzPjBjEjKjVjTjUjNjFjOjUiMjBjZjFjSiQfViLfNnctfJ2hdBnABXhffViLfNViDfHnf\
 J2heBnABXiBfViLfNViEfInfJ2hfBnABjzLjUjBjSjHjFjUjMjBjZjFjSiRfEXXfVMfARBCiNViFfJn\
 ndBffnfJ2iABnAEXzKjNjPjWjFiCjFjGjPjSjFiSfViLfNRBjiRfffAXzGjBjMjUiLjFjZiTfXzNjLj\
 FjZjCjPjBjSjEiTjUjBjUjFiUfXzLjFjOjWjJjSjPjOjNjFjOjUiVfjzIiTjDjSjJjQjUiViJiWfby2\
 iEBn0ABa2iEBb2iFBn0AGJ2iFBnASiIMXiJfQhLfVhZfBVVfOnftO2iHBby2iIBn0ABJ2iIBnASiIME\
 XiKfXiJfQhLfVhZfBVVfORCFdIFdRffnffACGEXiKfViIfMRCFdAFdHffnneHjBjEjKhAjGjPjSby2i\
 LBn0ABJ2iLBnASiIMEXiKfXiJfQhLfVhZfBVVfORCFdAFdIffnffJ2iNBnASzIjOjFjXiTjPjMjJjEi\
 XPEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffC\
 iNnViIfMeIjBjEjKhAjGjPjShAnXiOfVMfAXiPfVMfAFdBCzBhNiYQhLfVhdfEVVfOQhLfVhbfDVVfO\
 nnffnftJ2iOBnABXiQfViXfPnctfJ2iPBnABXhffViXfPQhLfVhbfDVVfOnfJ2iQBnAEXiSfViXfPRB\
 QhLfVhZfBVVfOffAVVfOAVhafCByBhMAChWVhafCnndAb2iYBn0ADJ2iYBnASiXPEXiMfXgcfVMfARG\
 ARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeGjBjEjKhAhahTXiO\
 fVMfAXiPfVMfAFdBXzQjXjPjSjLiBjSjFjBiEjVjSjBjUjJjPjOiZfVMfAffnftJ2iZBnABXiQfViXf\
 PnctfJ2iaBnABXhffViXfPXzNjXjPjSjLiBjSjFjBiTjUjBjSjUiafVMfAnfJ2idBnAEXzMjFjOjEiV\
 jOjEjPiHjSjPjVjQibfjPfnfARV4O0AiAD40BhAiX4P0AiAiA4G0AiAiI4M0AiAM40BiAhZ4B0AiAha\
 4C0AiAhb4D0AiAhd4E0AiAhe4F0AiAiD4H0AiAiE4I0AiAiF4J0AiAiG4K0AiAiH4L0AiAiL4N0AiAB\
 QAzJjDjSjFjBjUjFiBjEjKicA2ieBM2jABbyBn0AGJ2jBBnAEXhYfjPfRBFeOiOjFjXhAiOjVjMjMhA\
 iMjBjZjFjSffJ2jDBnASMAXNfXOfjPfnftJ2jEBnASTBXTfVMfAnftJ2jFBnASzJjJjTiBjMjUiEjPj\
 XjOidCXiTfXiUfXiVfjiWfnftO2jHBb2jJBn0AKJ2jJBnASzKjFjBjSjMjJjFjTjUiJjOieDXhffXhO\
 fVTfBnftJ2jKBnASzJjMjBjUjFjTjUiPjVjUifEXiBfXhOfVTfBnftJ2jLBnASzMjIjJjHjIjFjTjUi\
 JjOjEjFjYjAFXiCfXhOfVTfBnfta2jNBb2jOBn0AEJ2jOBnASXHQhLfVTfBVVfGnftO2jPBJ2jPBnAS\
 ieDXhffVXfHnffAChMXhffVXfHViefDnnnO2jQBJ2jQBnASifEXiBfVXfHnffAChWXiBfVXfHViffEn\
 nnO2jRBJ2jRBnASjAFXiCfVXfHnffAChWXiCfVXfHVjAfFnnnAVVfGBXLfVTfBByBhMJ2jUBnASzIjE\
 jVjSjBjUjJjPjOjBICiYViffEViefDnnnftJ2jXBnASgaJEXgbfXgcfVMfARBVjBfIffnftJ2jYBnAB\
 XhffVgafJViefDnfJ2jbBnAEXiSfVgafJRBEXXfVMfARBVjAfFffffa2jeBby2jfBn0ABJ2jfBnABXz\
 GjQjBjSjFjOjUjCfQhLfVTfBViAfKVgafJnfAViAfKAXLfVTfBByBhMO2kDBb2kEBn0AKJ2kEBnASzG\
 jJjOiUjJjNjFjDLXhffVgafJnftJ2kFBnASzHjPjVjUiUjJjNjFjEMXiBfVgafJnftJ2kHBnASzMjQj\
 PjTjJjUjJjPjOiQjSjPjQjFNEXgffEXgffVgafJRBFeJiUjSjBjOjTjGjPjSjNffRBFeIiQjPjTjJjU\
 jJjPjOffnftJ2kIBnASzJjTjDjBjMjFiQjSjPjQjGOEXgffEXgffVgafJRBFeJiUjSjBjOjTjGjPjSj\
 NffRBFeFiTjDjBjMjFffnftJ2kKBnASzKjDjVjSjSjFjOjUiQjPjTjHPXhJfVjFfNnftJ2kLBnASzMj\
 DjVjSjSjFjOjUiTjDjBjMjFjIQXhJfVjGfOnftJ2kNBnAEXzOjTjFjUiWjBjMjVjFiBjUiUjJjNjFjJ\
 fVjFfNRCVjDfLVjHfPffJ2kOBnAEXjJfVjFfNRCVjEfMVjHfPffJ2kQBnAEXjJfVjGfORCVjDfLVjIf\
 QffJ2kRBnAEXjJfVjGfORCVjEfMVjIfQffAVidfCnAChWXLfVTfBnndAb2kVBn0ADJ2kVBnASgaJEXg\
 bfXgcfVMfARBXiZfVMfAffnftJ2kWBnABXhffVgafJXiafVMfAnfO2kZBb2kaBn0AKJ2kaBnASjDLXh\
 ffVgafJnftJ2kbBnASjEMXiBfVgafJnftJ2kdBnASjFNEXgffEXgffVgafJRBFeJiUjSjBjOjTjGjPj\
 SjNffRBFeIiQjPjTjJjUjJjPjOffnftJ2keBnASjGOEXgffEXgffVgafJRBFeJiUjSjBjOjTjGjPjSj\
 NffRBFeFiTjDjBjMjFffnftJ2lABnASzDjQjPjTjKRXhJfVjFfNnftJ2lBBnASzFjTjDjBjMjFjLSXh\
 JfVjGfOnftJ2lDBnAEXjJfVjFfNRCVjDfLVjKfRffJ2lEBnAEXjJfVjFfNRCVjEfMVjKfRffJ2lGBnA\
 EXjJfVjGfORCVjDfLVjLfSffJ2lHBnAEXjJfVjGfORCVjEfMVjLfSffAVidfCnJ2lLBnAEXibfjPfnf\
 ATV4G0AiAid4C0AiAga4J0AiAiA4K0AiAie4D0AiAif4E0AiAjD4L0AiAjE4M0AiAjF4N0AiAjK4R0A\
 iAjG4O0AiAjI4Q0AiAjL4S0AiAjH4P0AiAjA4F0AiAM40BiAjB4I0AiAX4H0AiAT4B0AiAATAzKjDjS\
 jFjBjUjFiOjVjMjMjMA2lMBM2lQBbyBn0ABg2lSBbyBn0AOJ2lTBnASMAXNfXOfjPfnftO2lUBby2lV\
 Bn0ABf2lVBnAEjzFiFjSjSjPjSjNfRBFegciOjPhAjBjDjUjJjWjFhAjDjPjNjQjPjTjJjUjJjPjOhA\
 jGjPjVjOjEhOftAUIhJVMfAhJCRVMfAjSfnnnnnJ2lYBnAShZBXTfVMfAnftJ2lZBnAShaCXLfVhZfB\
 nftJ2lbBnASzFjDjPjMjPjSjODARDFdAFdAFdAfnftO2leBb2lfBn0ACJ2lfBnASzLjQjJjDjLjFjEi\
 DjPjMjPjSjPEEjhSfRBARDFdBFdBFdBfffnftO2mABby2mBBn0ABJ2mBBnASjODVjPfEnffACzDhBhd\
 hdjQVjPfEnnbnAXiTfXiUfXiVfjiWfnJ2mGBnAEXhYfjPfRBFePiOjFjXhAiTjPjMjJjEhAiMjBjZjF\
 jSffJ2mIBnASzCjUhRjRFEXzFjSjPjVjOjEjSfjzEiNjBjUjIjTfRBCzBhKjUXhOfVjOfDnndnfffnf\
 tJ2mJBnASzCjUhSjVGEXjSfjjTfRBCjUXhPfVjOfDnndnfffnftJ2mKBnASzCjUhTjWHEXjSfjjTfRB\
 CjUXhQfVjOfDnndnfffnftJ2mLBnASzEjUjFjYjUjXICiNCiNCiNCiNCiNCiNnVjRfFeBibnnneBhMV\
 jVfGnnnneBhMVjWfHnnnneBidnftJ2mMBnASzIjMjBjZjFjSiTjUjSjYJdUzChGhGjZCjQEXhRfVjOf\
 DnfnneFhQhMhQhMhQCjQEXhRfVjOfDnfnneHhRhMhRhMhRhMhRnnCiNnVjXfIeGiTjPjMjJjEhAnFeL\
 iTjPjMjJjEhAiMjBjZjFjSnftO2mPBb2mQBn0AGJ2mQBnASzNjTjFjMjFjDjUjFjEiMjBjZjFjSjaLX\
 hOfVhZfBnftO2mRBby2mSBn0ABf2mSBnAEjjNfRBFehCiTjFjMjFjDjUjFjEhAjMjBjZjFjShAjJjTh\
 AjJjOjWjBjMjJjEhAjPjShAjOjVjMjMhOftAUIhJVjafLCGVjafLnnbnnnJ2mUBnASjBMCiYXiBfVja\
 fLXhffVjafLnnnftJ2mWBnASzJjOjFjXiTjPjMjJjEhSjbKEXiMfXgcfVMfARGEXzGjTjQjMjJjDjFj\
 cfVjOfDRCFdAFdDffVjYfJXiOfVMfAXiPfVMfAFdBVjBfMffnftJ2meBnAEXiSfVjbfKRBVjafLffJ2\
 mfBnABXhffVjbfKXhffVjafLnfAChWVhafCnndAb2nBBn0ACJ2nBBnASjbKEXiMfXgcfVMfARGEXjcf\
 VjOfDRCFdAFdDffVjYfJXiOfVMfAXiPfVMfAFdBXiZfVMfAffnftJ2nJBnABXhffVjbfKXiafVMfAnf\
 J2nLBnAEXibfjPfnfABnzBjFjdnnANja4L0AiAjR4F0AiAjV4G0AiAjW4H0AiAjb4K0AiAjO4D0AiAM\
 40BiAhZ4B0AiAha4C0AiAjY4J0AiAjX4I0AiAjP4E0AiAjB4M0AiAANAzLjDjSjFjBjUjFiTjPjMjJj\
 EjeA2nSBM2nVBbyBn0AEJ2nWBnAEXhYfjPfRBFeOiOjFjXhAiUjFjYjUhAiMjBjZjFjSffJ2nXBnASM\
 AXNfXOfjPfnftO2nYBb2naBn0AFJ2naBnASjaBXhOfXTfVMfAnftJ2nbBnASzHjOjFjXiUjFjYjUjfC\
 EXzHjBjEjEiUjFjYjUkAfXgcfVMfAnfnftJ2ncBnABXhffVjffCXhffVjafBnfJ2ndBnABXiBfVjffC\
 XiBfVjafBnfJ2nfBnAEXiSfVjffCRBVjafBffAChWXLfXTfVMfAnndAb2ECn0ACJ2ECnASjfCEXkAfX\
 gcfVMfAnfnftJ2FCnABXhffVjffCXiafVMfAnfJ2JCnAEXibfjPfnfADja4B0AiAjf4C0AiAM40BiAA\
 DAzKjDjSjFjBjUjFiUjFjYjUkBA2KCM2MCbyBn0AGJ2NCnAEXhYfjPfRBFePiOjFjXhAiPjOjFhAiGj\
 SjBjNjFjSjTffJ2PCnASMAXNfXOfjPfnftJ2QCnASjaBXhOfXTfVMfAnftJ2RCnASzDjGjQjTkCCXzJ\
 jGjSjBjNjFiSjBjUjFkDfVMfAnftK2TCb2UCn0AEJ2UCnASiXEEXiMfXgcfVMfARGARDFd8kakZkZkZ\
 kZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZj\
 FjSXiOfVMfAXiPfVMfAFdBCzBhPkEnXkDfVMfAdBnffnftJ2VCnABXiQfViXfEnctfJ2WCnAEXiSfVi\
 XfERBVjafBffJ2YCnABXhffViXfECiNXhffVjafBCjUVVfDXzNjGjSjBjNjFiEjVjSjBjUjJjPjOkFf\
 VMfAnnnnnfASVDVzBjYkGfFnftChWVVfDnndyBTVDyBtJ2gaCnAEXibfjPfnfAGV4D0AiAkG40BhAiX\
 4E0AiAja4B0AiAkC4C0AiAM40BiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiMkHA2gbCM2gdCby\
 Bn0AGJ2geCnAEXhYfjPfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJ2hACnASMAXNfXOfjPfnft\
 J2hBCnASjaBXhOfXTfVMfAnftJ2hCCnASkCCXkDfVMfAnfta2hECb2hFCn0AEJ2hFCnASiXEEXiMfXg\
 cfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKj\
 VjTjUjNjFjOjUhAiMjBjZjFjSXiOfVMfAXiPfVMfAFdBCkEnXkDfVMfAdBnffnftJ2hGCnABXiQfViX\
 fEnctfJ2hHCnAEXiSfViXfERBVjafBffJ2hJCnABXhffViXfECiYXiBfVjafBCjUVVfDXkFfVMfAnnn\
 nnfAVVfDBVkGfFByBhMJ2hLCnAEXibfjPfnfAGV4D0AiAkG40BhAiX4E0AiAja4B0AiAkC4C0AiAM40\
 BiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiSkIA2hMCM2hOCbyBn0AFJ2hQCnASMAXNfXOfjPfn\
 ftJ2hRCnASjaBXhOfXTfVMfAnftJ2hUCnASzFjDjPjVjOjUkJDQhLfjBfjCfnftK2hWCb2hZCn0AHJ2\
 hZCnASiXCEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZk\
 ZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiOfVMfAXiPfVMfAFdBCjUXkFfVMfAnnd8kFnL\
 iRlYgekFnPhfffnffJ2haCnABXiQfViXfCnctfJ2hbCnAEXiSfViXfCRBVjafBffJ2hdCnABXWfViXf\
 CncffJ2heCnABjzBjZkKfCiNXzEjUjJjNjFkLfVMfACjUVkJfDXkFfVMfAnnnnnfJ2iACnABXhffViX\
 fCjkKfnfJ2iDCnASkJDCiYnnndBntfASVEVkGfFnftChWVVfEnndyBTVEyBtJ2iHCnABXTfVMfAAnnf\
 AGV4E0AiAkG40BhAiX4C0AiAja4B0AiAkJ4D0AiAM40BiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjF\
 jSiNkMA2iICM2iLCbyBn0AKJ2iMCnAEXhYfjPfRBFeViDjSjFjBjUjFhAiNjBjTjLhAjGjSjPjNhAiU\
 jFjYjUffJ2iNCnASMAXNfXOfjPfnftJ2iOCnASzOjDjSjFjBjUjFiTjIjBjQjFjTiJiEkNBEXzRjGjJ\
 jOjEiNjFjOjViDjPjNjNjBjOjEiJjEkOfjPfRBFeXiDjSjFjBjUjFhAiTjIjBjQjFjThAjGjSjPjNhA\
 iUjFjYjUffnftJ2iPCnAEXzMjPjQjFjOiJjOiWjJjFjXjFjSkPfVMfAnfJ2iQCnASzJjUjFjYjUiMjB\
 jZjFjSkQCXhOfXTfVMfAnftJ2iRCnASzKjHjMjPjCjBjMiUjFjYjUkRDEXhRfXhJfEXgffVkQfCRBFe\
 LiTjPjVjSjDjFhAiUjFjYjUffnfnftJ2iTCnAEXhHfjPfRBVkNfBffJ2iVCnASzKjTjIjBjQjFiMjBj\
 ZjFjSkSEXhOfXTfVMfAnfta2iWCb2iXCn0AEa2iXCby2iYCn0ABO2iYCby2iZCn0ABJ2iZCnABXhEfE\
 XgffEXgffVkSfERBFeIiDjPjOjUjFjOjUjTffRBQhLfVkRfDViAfGffncffACKViAfGVVfFnnby2idC\
 n0ABJ2idCnABXhEfEXgffEXgffVkSfERBFeIiDjPjOjUjFjOjUjTffRBQhLfVkRfDViAfGffnctfAVi\
 AfGAXLfVkRfDByBhMJ2jBCnASzDjEjVjQkTHEXzJjEjVjQjMjJjDjBjUjFkUfVkSfEnfnftJ2jCCnAB\
 XiJfVkTfHQhLfVkRfDVVfFnfJ2jDCnAEXiSfVkTfHRBXhOfXTfVMfAffAVVfFAXLfVkRfDByBhMJ2jF\
 CnAEXibfjPfnfAIV4F0AiAiA4G0AiAM40BiAkN4B0AiAkQ4C0AiAkR4D0AiAkS4E0AiAkT4H0AiAAIA\
 zOjDjSjFjBjUjFiUjFjYjUiNjBjTjLkVA2jGCM2jICbyBn0AJJ2jKCnASMAXNfXOfjPfnftJ2jLCnAS\
 kNBEXkOfjPfRBFeWiDjSjFjBjUjFhAiNjBjTjLjThAjGjSjPjNhAiUjFjYjUffnftJ2jMCnAEXkPfVM\
 fAnfJ2jNCnASkQCXhOfXTfVMfAnftJ2jOCnASkRDEXhRfXhJfEXgffVkQfCRBFeLiTjPjVjSjDjFhAi\
 UjFjYjUffnfnftJ2jPCnAEXhHfjPfRBVkNfBffJ2jRCnASkSEXhOfXTfVMfAnfta2jSCb2jTCn0AEa2\
 jTCby2jUCn0ABO2jUCby2jVCn0ABJ2jVCnABXhEfEXgffEXgffVkSfERBFeIiDjPjOjUjFjOjUjTffR\
 BQhLfVkRfDViAfGffncffACKViAfGVVfFnnby2jYCn0ABJ2jYCnABXhEfEXgffEXgffVkSfERBFeIiD\
 jPjOjUjFjOjUjTffRBQhLfVkRfDViAfGffnctfAViAfGAXLfVkRfDByBhMJ2jbCnASkTHEXkUfVkSfE\
 nfnftJ2jcCnABXiJfVkTfHQhLfVkRfDVVfFnfJ2jdCnAEXiSfVkTfHRBXhOfXTfVMfAffAVVfFAXLfV\
 kRfDByBhMJ2kACnAEXhKfXhOfXTfVMfAnfAIV4F0AiAiA4G0AiAM40BiAkN4B0AiAkQ4C0AiAkR4D0A\
 iAkS4E0AiAkT4H0AiAAIAzPjDjSjFjBjUjFiUjFjYjUiNjBjTjLhSkWA2kCCNJNnASzHjNjZiQjBjOj\
 FjMkXAdCRVzHjUjIjJjTiPjCjKkYfRjzFiQjBjOjFjMkZfnnVkYfREjzGiXjJjOjEjPjXkafREFeHjQ\
 jBjMjFjUjUjFFeNjNjVjGjGjJjOhAjMjBjZjFjSjTjzJjVjOjEjFjGjJjOjFjEkbfWzGiPjCjKjFjDj\
 UkcBzKjSjFjTjJjajFjBjCjMjFkdFctftnftJUnABXzNjBjMjJjHjOiDjIjJjMjEjSjFjOkefVkXfAA\
 RCFeEjMjFjGjUFeDjUjPjQfnfJVnABXzHjNjBjSjHjJjOjTkffVkXfAndFfJWnABXzHjTjQjBjDjJjO\
 jHlAfVkXfAndEfJXnABXkefVkXfAARCFeEjGjJjMjMFeEjGjJjMjMfnfJYnABXzLjPjSjJjFjOjUjBj\
 UjJjPjOlBfVkXfAneFjTjUjBjDjLfJgdnASzIjHjSjPjVjQiPjOjFlCBEXzDjBjEjElDfVkXfARDFeF\
 jHjSjPjVjQjkbfFeIjHjSjPjVjQiPjOjFffnftJgenABXkefVlCfBARCFeEjGjJjMjMFeEjGjJjMjMf\
 nfJhAnABXkffVlCfBndAfJhBnABXlAfVlCfBndDfOhCbhDn0AhDJhDnASzDjBjEjKlECEXlDfVlCfBR\
 DFeGjCjVjUjUjPjOjkbfFeDiBiEiKffnftJhEnASzDjOjVjMlFDEXlDfVlCfBRDFeGjCjVjUjUjPjOj\
 kbfFeEiOjVjMjMffnftJhFnASjXEEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeEiUjFjYjUffnftJhGn\
 ASzFjTjPjMjJjElGFEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeFiTjPjMjJjEffnftJhHnASzHiNjGj\
 SjBjNjFjTlHGEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeB2kSBffnftJhInASzIjEjSjPjQiEjPjXjO\
 lIHEXlDfVlCfBRDFeMjEjSjPjQjEjPjXjOjMjJjTjUjkbfAREFdBFdCFdDFdEfffnftJhJnABXzJjTj\
 FjMjFjDjUjJjPjOlJfVlIfHndCfJhLnASzGjSjFjOjBjNjFlKIEXlDfVlCfBRDFeGjCjVjUjUjPjOjk\
 bfFeGjSjFjOjBjNjFffnftJhOnASzIjHjSjPjVjQiUjXjPlLJEXlDfVkXfARDFeFjHjSjPjVjQjkbfF\
 eIjHjSjPjVjQiUjXjPffnftJhQnABXkefVlLfJARCFeEjGjJjMjMFeEjGjJjMjMfnfJhRnABXkffVlL\
 fJndAfJhSnABXlAfVlLfJndDfJhUnABXiPfXzLjNjBjYjJjNjVjNiTjJjajFlMfVlLfJndZfJhWnASz\
 EjBjEjKhSlNKEXlDfVlLfJRDFeGjCjVjUjUjPjOjkbfFeDiBiEiKffnftJhXnASzEjOjVjMhSlOLEXl\
 DfVlLfJRDFeGjCjVjUjUjPjOjkbfFeEiOjVjMjMffnftJhYnASzFjUjFjYjUhSlPMEXlDfVlLfJRDFe\
 GjCjVjUjUjPjOjkbfFeEiUjFjYjUffnftJhZnASzGjTjPjMjJjEhSlQNEXlDfVlLfJRDFeGjCjVjUjU\
 jPjOjkbfFeFiTjPjMjJjEffnftJhanASzIiNjGjSjBjNjFjThSlROEXlDfVlLfJRDFeGjCjVjUjUjPj\
 OjkbfFeB2kSBffnftJhbnASzJjEjSjPjQiEjPjXjOhSlSPEXlDfVlLfJRDFeMjEjSjPjQjEjPjXjOjM\
 jJjTjUjkbfAREFdBFdCFdDFdEfffnftJhcnABXlJfVlSfPndCfJhenASzHjSjFjOjBjNjFhSlTQEXlD\
 fVlLfJRDFeGjCjVjUjUjPjOjkbfFeGjSjFjOjBjNjFffnftJiBnABXzIjPjOiDjIjBjOjHjFlUfVlIf\
 HNyBnAMiBbyBn0ABJiCnABjCfXlJfjlIfnf0DhLCiDnfJiEnABXlUfVlSfPNyBnAMiEbyBn0ABJiFnA\
 BjCfXlJfjlSfnf0DhLCiGnfJiInABXzHjPjOiDjMjJjDjLlVfVlEfCNyBnAMiIbyBn0ACJiKnAEjicf\
 RBjDfffJiLnABjDfCiNnnndBnt0DhLCiMnfJiPnABXlVfVlFfDNyBnAMiPbyBn0ABJiQnAEjjMfnf0D\
 hLCiRnfJiTnABXlVfVlHfGNyBnAMiTbyBn0ABOiUbyiVn0ABJiVnAEjQfRBFeVjQjMjFjBjTjFhAjTj\
 FjMjFjDjUhAjBhAjMjBjZjFjSffACGXLfXTfXNfXOfjPfnndAbiYn0ADJiYnAEXhYfjPfRBFePiOjFj\
 XhAiPjOjFhAiGjSjBjNjFjSjTffJiZnAEjkMfRBQhLfjBfjCfffJianAEXibfjPfnf0DhLCicnfJien\
 ABXlVfVjXfENyBnAMiebyBn0ABJifnAEjkBfnf0DhLCjAnfJjCnABXlVfVlKfINyBnAMjCbyBn0ACJj\
 DnAEXhYfjPfRBFeGiSjFjOjBjNjFffJjEnAEjzWjSjFjOjBjNjFiBjEjKjVjTjUjNjFjOjUiMjBjZjF\
 jSjTlWfnf0DhLCjFnfJjGnABXlVfVlTfQNyBnAMjGbyBn0ADJjHnAEXhYfjPfRBFeGiSjFjOjBjNjFf\
 fJjInAEjlWfnfJjJnAEXibfjPfnf0DhLCjKnfJjNnABXlVfVlNfKNyBnAMjNbyBn0ACJjOnAEjicfRB\
 jDfffJjPnABjDfCiNnnndBnt0DhLCjQnfJjSnABXlVfVlOfLNyBnAMjSbyBn0ABJjTnAEjjMfnf0DhL\
 CjUnfJjWnABXlVfVlRfONyBnAMjWbyBn0ABOjXbyjYn0ABJjYnAEjQfRBFeVjQjMjFjBjTjFhAjTjFj\
 MjFjDjUhAjBhAjMjBjZjFjSffACGXLfXTfXNfXOfjPfnndAbjcn0ADJjcnAEXhYfjPfRBFePiOjFjXh\
 AiPjOjFhAiGjSjBjNjFjSjTffJjenAEjkMfRBQhLfjBfjCfffJjfnAEXibfjPfnf0DhLCkCnfJkEnAB\
 XlVfVlPfMNyBnAMkEbyBn0ABJkFnAEjkBfnf0DhLCkGnfJkInABXlVfVlGfFNyBnAMkIbyBn0ABgkJb\
 yBn0ABJkLnAEjjefnfABnjdnbyBn0ABJkOnAEjQfRBCiNCiNCiNCiNCiNnEXhRfjjdfnfeYiFjSjSjP\
 jShAjJjOhAjTjPjMjJjEhOjPjOiDjMjJjDjLhaKnnneHKiMjJjOjFhahAXzEjMjJjOjFlXfjzBhElYf\
 nnnneIKiTjUjBjDjLhahAXzFjTjUjBjDjLlZfjlYfnnff0DhLCkSnfJkUnABXlVfVlQfNNyBnAMkUby\
 Bn0ABgkVbyBn0ABJkXnAEjjefnfABnjdnbyBn0ABJkanAEjQfRBCiNCiNCiNCiNCiNnEXhRfjjdfnfe\
 ZiFjSjSjPjShAjJjOhAjTjPjMjJjEhShOjPjOiDjMjJjDjLhaKnnneHKiMjJjOjFhahAXlXfjlYfnnn\
 neIKiTjUjBjDjLhahAXlZfjlYfnnff0DhLCkenfACGjFfnneZjEjFjWjFjMjPjQjFjEhAjCjZhAjNjV\
 jGjGjJjOjNjJjYhAhahTnJlCnABXzKjPjOiSjFjTjJjajJjOjHlafVkXfABXzIjPjOiSjFjTjJjajFl\
 bfVkXfANyBnAMlCbyBn0AEJlEnABXlBfjlCfdChWXiOfXzEjTjJjajFlcfjkXfXiPfXlcfjkXfnnFeD\
 jSjPjXFeGjDjPjMjVjNjOnfJlGnABXlBfjlLfdChWXiOfXlcfjkXfXiPfXlcfjkXfnnFeDjSjPjXFeG\
 jDjPjMjVjNjOnfOlIblKn0ACJlKnABXzHjWjJjTjJjCjMjFldfjlLfncffJlMnABXldfjlCfnctfAUj\
 ZChWXiOfXlcfjkXfnndZChMXiOfXlcfjkXfXiPfXlcfjkXfnnnnblQn0ACJlQnABXldfjlCfncffJlS\
 nABXldfjlLfnctfJlWnAEXzGjSjFjTjJjajFlefXzGjMjBjZjPjVjUlffjkXfnf0DhLClYnfnfOlabl\
 cn0ACJlcnAEXzGjDjFjOjUjFjSmAfVkXfAnfJlenAEXzEjTjIjPjXmBfVkXfAnfACRVkXfAjkafnnbm\
 Cn0ACJmCnAEXlffXlffVkXfARBFctffJmEnAEXlefXlffVkXfAnfASlT4Q0AiAjX4E0AiAlK4I0AiAl\
 P4M0AiAkX40BiAlC4B0AiAlE4C0AiAlF4D0AiAlG4F0AiAlH4G0AiAlI4H0AiAlL4J0AiAlN4K0AiAl\
 O4L0AiAlQ4N0AiAlR4O0AiAlS4P0AiAkY40BhABRAzIjCjVjJjMjEifiViJmCA2kDCM2kFCbyBn0AEJ\
 2kGCnASMAXNfXOfjPfnftO2kHCb2kICn0ACJ2kICnAEjQfRBFegciQjMjFjBjTjFhAjTjFjMjFjDjUh\
 AjBhAjDjPjNjQjPjTjJjUjJjPjOhOffZ2kJCnAnAUIhJVMfAhJCRVMfAjSfnnnnnJ2kNCnASgcBXgcf\
 VMfAnfta2kOCb2kPCn0ACJ2kPCnASXDQhLfVgcfBVVfCnftO2kQCb2kRCn0ACJ2kRCnASzHjFjGjGjF\
 jDjUjTmDEEXgffVXfDRBFeSiBiEiCiFhAiFjGjGjFjDjUhAiQjBjSjBjEjFffnftO2kSCb2kTCn0AEJ\
 2kTCnASzHjOjFjXiOjBjNjFmEFneAfta2kUCb2kVCn0ACJ2kVCnASzGjFjGjGjFjDjUmFHEXgffVmDf\
 ERBViAfGffnftO2kWCb2kXCn0ACJ2kXCnASzEjOjJjDjLmGIUIQhLfjzJjOjJjDjLjOjBjNjFjTmHfX\
 iJfVmFfHXiJfVmFfHnnnftJ2kYCnASmEFCiNnCiNVmGfInneBhAnnntfACzDhdhdhdmIEXzHjJjOjEj\
 FjYiPjGmJfjzKjFjYjDjMjVjTjJjPjOjTmKfRBXiJfVmFfHffnndyBnAViAfGBXzNjOjVjNiQjSjPjQ\
 jFjSjUjJjFjTmLfVmDfEByBZJ2kbCnASmEFEXzEjUjSjJjNmMfVmEfFnfnffO2kcCby2kdCn0ABJ2kd\
 CnABXiJfVXfDVmEfFnfACjQVmEfFnneAnAChWXmLfVmDfEnndAnAUjZCRVXfDjzHiBiWiMjBjZjFjSm\
 NfnnXiQfVXfDnnnAVVfCBXLfVgcfBByBZAJmF4H0AiAV4C0AiAX4D0AiAiA4G0AiAgc4B0AiAmE4F0A\
 iAM40BiAmG4I0AiAmD4E0AiAAJAlWA2lCCM2lGCbyBn0ACJ2lHCnASMAXNfXOfjPfnftO2lICb2lJCn\
 0ACJ2lJCnAEjQfRBFegeiQjMjFjBjTjFhAjTjFjMjFjDjUhAjBjUhAjMjFjBjTjUhAhRhAjMjBjZjFj\
 SffZ2lKCnAFcfACGXLfXTfVMfAnndAb2lMCn0ACJ2lMCnASgcBXTfVMfAnfta2lNCb2lOCn0AGJ2lOC\
 nAEXhHfjPfRBEXkOfjPfRBFehEiDjFjOjUjFjShAiBjOjDjIjPjShAiQjPjJjOjUhAjJjOhAiMjBjZj\
 FjShAiDjPjOjUjFjOjUffffJ2lPCnAEXhFfEXgffQhLfVgcfBVVfCRBFeIiQjPjTjJjUjJjPjOffRBA\
 RCCkEXiOfXNfXOfjPfnndCCkEXiPfXNfXOfjPfnndCfffJ2lQCnAEXhFfEXgffQhLfVgcfBVVfCRBFe\
 FiTjDjBjMjFffRBARCFdjEFdjEfffJ2lRCnAEXhFfEXgffQhLfVgcfBVVfCRBFeHiPjQjBjDjJjUjZf\
 fRBFdjEffJ2lTCnAEXhFfEXgffQhLfVgcfBVVfCRBFeIiSjPjUjBjUjJjPjOffRBFdAffO2lVCby2lW\
 Cn0ABJ2lWCnAEXhFfEXgffQhLfVgcfBVVfCRBFeMiBjVjEjJjPhAiMjFjWjFjMjTffRBARCFdAFdAff\
 fACKEXgffQhLfVgcfBVVfCRBFeMiBjVjEjJjPhAiMjFjWjFjMjTffnnbnAVVfCAXLfVgcfBByBhMADV\
 4C0AiAgc4B0AiAM40BiAADAzOjSjFjTjFjUiUjSjBjOjTjGjPjSjNmOA2lcCBJ2mACnAEjmCfRBVkYf\
 AffABkY40BhAB0AhLC2mCCRBezEjUjIjJjTmPfffAFB40BiAC4B0AiAD4C0AiAF4E0AiAE4D0AiAAFA\
 hLByB\");
