//tested on ae20-25
//source code availabe upon request
var  read_me = "developed by muffinmix :3";

    /* =====================================
                    place file in [Scipt UI Panels] folder
                                typically found at :
    C:\Program Files\Adobe\Adobe After Effects 20XX\Support Files\Scripts\ScriptUI Panels 
    ========================================= */

    /* ============================
          Button Functionality
    ============================== 
ADJ: 
            CLICK creates trimmed adjustment layers for each layer selected
            ALT-CLICK creates 1 adjustment layer from the first to last layer selected
            if no layer is selected, creates adj layer spanning the full comp duration

NULL: 
            CLICK creates a trimmed null autoparented to selected layers
            ALT-CLICK auto adds POS and SCALE keyframes  
            if no layer is selected, creates null spanning the full comp duration

TEXT: 
            CLICK creates a trimmed text layer for each layer you have selected. 
            if no layer is selected, creates text spanning the full comp duration
            
SOLID: 
            CLICK creates a black solid trimmed to first selected layers
            ALT-CLICK lets you select the solid color beforehand
            if no layer is selected, creates solid spanning the full comp duration

ƒ: 
            CLICK creates "one framers" at the location of your Current Time Indicator (CTI) / playhead
            -the amount is based on the number selected from the drop down menu on the right
    
rename: 
            renames adjustment layers to the effects applied
            *cred to kaim for the help
            ∨∨Custom with the arrays below∨∨
            
       ==================================*/

// custom renames 

    // Define nicknames (short names for effects)
var nicknames = {
    "Looks": "MBL",
    "Twixtor Pro": "twix",
    "Gaussian Blur": "GausBlur",
    "S_Shake": "Shake",
    "Curves": "C"
    // Add more as needed
};

    // Define exclusions (these effects will be ignored)
var exclusions = [
    "Motion Tile",
    "CC RepeTile",
    "Slider Control",
    "Point Control"
    // Add more as needed
];

// dont touch  =^w^=
eval("@JSXBIN@ES@2.0@MyBbyBn0AGJBnASzEjDjPjOjWByBARFFdyBFdAFdBFdCFdDfnftJCnA\
SzCjYhRCyBndDftJDnASzIjBjEjKiDjPjVjOjUDyBndBftJEnASzRjQjJjDjLjFjEiDjPjMjPjSiHjMjPjCjBjMEyB\
nbftOIbyJn0ABJJnASzHjSjFjBjEifjNjFFyBneAftACzChdhdGVFfyBnnbnJ2mGCnAENyBnAMMbyBnA\
EMObyBnALMmLbyBn0AWOmMbymNn0ABJmNnASzKjTjUjBjSjUiWjBjMjVjFHKARDFdBFdBFdBfnffAUzC\
jcjcIhzBhBJVHfKCzChBhdKXzGjMjFjOjHjUjILfVHfKnndDnnnJmQnASzEjDjPjNjQMAXzKjBjDjUjJ\
jWjFiJjUjFjNNfXzHjQjSjPjKjFjDjUOfjzDjBjQjQPfnftOmRbmSn0ACJmSnAEjzFjBjMjFjSjUQfRB\
FeTiOjPhAjDjPjNjQhAjJjThAjTjFjMjFjDjUjFjEffZmTnAFbAUIhJVMfAhJCzKjJjOjTjUjBjOjDjF\
jPjGRVMfAjzIiDjPjNjQiJjUjFjNSfnnnnnJmWnASzOjTjFjMjFjDjUjFjEiMjBjZjFjSjTTBAnnftam\
XbymYn0ABOmYJmYnAEXzEjQjVjTjIUfVTfBRBVzBjJVfCffAXzIjTjFjMjFjDjUjFjEWfEXzFjMjBjZj\
FjSXfVMfARBVVfCffnAVVfCBXzJjOjVjNiMjBjZjFjSjTYfVMfAByBzChchdZJmcnASzHjOjFjXiOjVj\
MjMgaDEXzHjBjEjEiOjVjMjMgbfXzGjMjBjZjFjSjTgcfVMfAnfnftJmdnASzPjOjFjXiDjPjMjPjSiD\
jPjOjUjSjPjMgdEEXzLjBjEjEiQjSjPjQjFjSjUjZgefEXzIjQjSjPjQjFjSjUjZgffVgafDRBFeSiBi\
EiCiFhAiFjGjGjFjDjUhAiQjBjSjBjEjFffRBFeSiBiEiCiFhAiDjPjMjPjShAiDjPjOjUjSjPjMffnf\
tJmenASzMjUjIjFiDjPjMjPjSiQjSjPjQhAFEXgffVgdfERBFeXiBiEiCiFhAiDjPjMjPjShAiDjPjOj\
UjSjPjMhNhQhQhQhRffnftJnBnASzQjPjSjJjHiTjIjZiDjPjOjEjJjUjJjPjOhBGXzNjIjJjEjFiTjI\
jZiMjBjZjFjSjThCfVMfAnftOnCJnCnABXhCfVMfAnctfACGVhBfGnncfnJnDnABXzDjTjIjZhDfVgaf\
DnctfJnEnABXzHjFjOjBjCjMjFjEhEfVgafDncffJnHnAEXzIjTjFjUiWjBjMjVjFhFfVhAfFRBVHfKf\
fJnKnASzLjFjEjJjUiWjBjMjVjFiJiEhGHnd2mAIftJnLnABXWfVhAfFnctfJnMnAEXzOjFjYjFjDjVj\
UjFiDjPjNjNjBjOjEhHfjPfRBVhGfHffJnPnASzGjSjFjTjVjMjUhIIXzFjWjBjMjVjFhJfVhAfFnftO\
nSbynTn0ABJnTnAEXzGjSjFjNjPjWjFhKfVgafDnfAVgafDnJnXnABXhCfVMfAVhBfGnfanabynbn0AB\
JnbnABXWfEXXfVMfARBQzAhLfVTfBVVfCffnctfAVVfCAXLfVTfBByBzBhchMJnfnASzPjTjUjBjSjUi\
WjBjMjVjFiJjOiSjHjChNJARDXzBhQhOfVHfKXzBhRhPfVHfKXzBhShQfVHfKfnftZ2ABnAdCGEXzIjU\
jPiTjUjSjJjOjHhRfVhIfInfEXhRfVhNfJnfnnFbVhIfIALV4C0AiAT4B0AiAH40BhAM40BiAga4D0Ai\
Agd4E0AiAhA4F0AiAhB4G0AiAhG4H0AiAhN4J0AiAhI4I0AiABKAzXiHjPjPjEiCjPjZiOjJjOjKjBiD\
jPjMjPjSiQjJjDjLjFjShSA2BBM2DBbyBn0ADJ2EBnASzDjOjVjNhTAXhOfVzFjBjSjSjBjZhUfCnftO\
2FBby2HBn0ABa2HBby2IBn0ABO2IBby2JBn0ABJ2JBnAShTAQhLfVhUfCVVfBnffAChMQhLfVhUfCVVf\
BVhTfAnnnAVVfBBXLfVhUfCByBhMAVzBjChVfDby2PBn0ABa2PBby2QBn0ABO2QBby2RBn0ABJ2RBnAS\
hTAQhLfVhUfCVVfBnffACzBhehWQhLfVhUfCVVfBVhTfAnnnAVVfBBXLfVhUfCByBhMZ2VBnAVhTf0AE\
V4B0AiAhT40BiAhV4B0AhAhU40BhACCAzGjNjJjOjNjBjYhXA2WBM2YBbyBn0AGJ2ZBnAEXzOjCjFjHj\
JjOiVjOjEjPiHjSjPjVjQhYfjPfRBFeUiOjFjXhAiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSffJ2gaBn\
ASMAXNfXOfjPfnftJ2gbBnASzRjTjFjMjFjDjUjFjEiMjBjZjFjSjTiBjSjShZBXTfVMfAnftJ2gcBnA\
SzLjOjVjNiTjFjMjFjDjUjFjEhaCXLfXTfVMfAnftO2geBb2hABn0AFJ2hABnASzFjJjOiQjUjThbDEj\
zFiBjSjSjBjZhcfntnftJ2hBBnASzGjPjVjUiQjUjThdEEjhcfntnftJ2hCBnASzDjJjOjEheFEjhcfn\
tnfta2hFBb2hGBn0ADJ2hGBnAEXUfVhbfDRBXzHjJjOiQjPjJjOjUhffQhLfVhZfBVzBjKiAfGffJ2hH\
BnAEXUfVhdfERBXzIjPjVjUiQjPjJjOjUiBfQhLfVhZfBViAfGffJ2hIBnAEXUfVhefFRBXzFjJjOjEj\
FjYiCfQhLfVhZfBViAfGffAViAfGAVhafCByBhMO2hMBb2hOBn0ANJ2hOBnASzDiNiJiOiDHEjhXfRCV\
hbfDFdBffnftJ2hPBnASzDiNiBiYiEIEjhXfRCVhdfEFdAffnftJ2hQBnASzFjNjJjOjJjOiFJEjhXfR\
CVhefFFdBffnftJ2hRBnASzMjGjJjSjTjUiJjOiQjPjJjOjUiGKViDfHnftJ2hSBnASzMjMjBjTjUiPj\
VjUiQjPjJjOjUiHLViEfInftJ2hUBnASzBjTiIMXzEjOjBjNjFiJfXhOfVhZfBnftO2hVBby2hWBn0AB\
J2hWBnASiIMEXzJjTjVjCjTjUjSjJjOjHiKfXiJfXhOfVhZfBRCFdJFdRffnffACGEXiKfViIfMRCFdA\
FdIffnneHjBjEjKhAjGjPjSby2hZBn0ABJ2hZBnASiIMEXiKfXiJfXhOfVhZfBRCFdAFdIffnffJ2hdB\
nASzIjBjEjKiMjBjZjFjSiLNEXzIjBjEjEiTjPjMjJjEiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfF\
d8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffCzBhLiNnViIfMeIjBjEjKhAjGjPjShAnXzFjXjJjEj\
UjIiOfVMfAXzGjIjFjJjHjIjUiPfVMfAFdBFdBffnftJ2heBnABXzPjBjEjKjVjTjUjNjFjOjUiMjBjZ\
jFjSiQfViLfNnctfJ2hfBnABXhffViLfNViDfHnfJ2iABnABXiBfViLfNViEfInfJ2iBBnABjzLjUjBj\
SjHjFjUjMjBjZjFjSiRfEXXfVMfARBCiNViFfJnndBffnfJ2iCBnAEXzKjNjPjWjFiCjFjGjPjSjFiSf\
ViLfNRBjiRfffAXzGjBjMjUiLjFjZiTfXzNjLjFjZjCjPjBjSjEiTjUjBjUjFiUfXzLjFjOjWjJjSjPj\
OjNjFjOjUiVfjzIiTjDjSjJjQjUiViJiWfby2iGBn0ABa2iGBb2iHBn0AGJ2iHBnASiIMXiJfQhLfVhZ\
fBVVfOnftO2iJBby2iKBn0ABJ2iKBnASiIMEXiKfXiJfQhLfVhZfBVVfORCFdIFdRffnffACGEXiKfVi\
IfMRCFdAFdHffnneHjBjEjKhAjGjPjSby2iNBn0ABJ2iNBnASiIMEXiKfXiJfQhLfVhZfBVVfORCFdAF\
dIffnffJ2iPBnASzIjOjFjXiTjPjMjJjEiXPEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZ\
kZkZkZkZmJhfFd8kakZkZkZkZkZmJhffCiNnViIfMeIjBjEjKhAjGjPjShAnXiOfVMfAXiPfVMfAFdBC\
zBhNiYQhLfVhdfEVVfOQhLfVhbfDVVfOnnffnftJ2iQBnABXiQfViXfPnctfJ2iRBnABXhffViXfPQhL\
fVhbfDVVfOnfJ2iSBnAEXiSfViXfPRBQhLfVhZfBVVfOffAVVfOAVhafCByBhMAChWVhafCnndAb2iaB\
n0ADJ2iaBnASiXPEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZ\
kZkZkZmJhffFeGjBjEjKhAhahTXiOfVMfAXiPfVMfAFdBXzQjXjPjSjLiBjSjFjBiEjVjSjBjUjJjPjO\
iZfVMfAffnftJ2ibBnABXiQfViXfPnctfJ2icBnABXhffViXfPXzNjXjPjSjLiBjSjFjBiTjUjBjSjUi\
afVMfAnfJ2ifBnAEXzMjFjOjEiVjOjEjPiHjSjPjVjQibfjPfnfARha4C0AiAV4O0AiAhb4D0AiAhd4E\
0AiAhe4F0AiAiA4G0AiAiD4H0AiAiI4M0AiAiE4I0AiAiF4J0AiAiG4K0AiAiH4L0AiAD40BhAiL4N0A\
iAM40BiAiX4P0AiAhZ4B0AiABQAzJjDjSjFjBjUjFiBjEjKicA2jABM2jCBbyBn0AGJ2jDBnAEXhYfjP\
fRBFeOiOjFjXhAiOjVjMjMhAiMjBjZjFjSffJ2jFBnASMAXNfXOfjPfnftJ2jGBnASTBXTfVMfAnftJ2\
jHBnASzJjJjTiBjMjUiEjPjXjOidCXiTfXiUfXiVfjiWfnftO2jJBb2jLBn0AKJ2jLBnASzKjFjBjSjM\
jJjFjTjUiJjOieDXhffXhOfVTfBnftJ2jMBnASzJjMjBjUjFjTjUiPjVjUifEXiBfXhOfVTfBnftJ2jN\
BnASzMjIjJjHjIjFjTjUiJjOjEjFjYjAFXiCfXhOfVTfBnfta2jPBb2jQBn0AEJ2jQBnASXHQhLfVTfB\
VVfGnftO2jRBJ2jRBnASieDXhffVXfHnffAChMXhffVXfHViefDnnnO2jSBJ2jSBnASifEXiBfVXfHnf\
fAChWXiBfVXfHViffEnnnO2jTBJ2jTBnASjAFXiCfVXfHnffAChWXiCfVXfHVjAfFnnnAVVfGBXLfVTf\
BByBhMJ2jWBnASzIjEjVjSjBjUjJjPjOjBICiYViffEViefDnnnftJ2jZBnASgaJEXgbfXgcfVMfARBV\
jBfIffnftJ2jaBnABXhffVgafJViefDnfJ2jdBnAEXiSfVgafJRBEXXfVMfARBVjAfFffffa2kABby2k\
BBn0ABJ2kBBnABXzGjQjBjSjFjOjUjCfQhLfVTfBViAfKVgafJnfAViAfKAXLfVTfBByBhMO2kFBb2kG\
Bn0AKJ2kGBnASzGjJjOiUjJjNjFjDLXhffVgafJnftJ2kHBnASzHjPjVjUiUjJjNjFjEMXiBfVgafJnf\
tJ2kJBnASzMjQjPjTjJjUjJjPjOiQjSjPjQjFNEXgffEXgffVgafJRBFeJiUjSjBjOjTjGjPjSjNffRB\
FeIiQjPjTjJjUjJjPjOffnftJ2kKBnASzJjTjDjBjMjFiQjSjPjQjGOEXgffEXgffVgafJRBFeJiUjSj\
BjOjTjGjPjSjNffRBFeFiTjDjBjMjFffnftJ2kMBnASzKjDjVjSjSjFjOjUiQjPjTjHPXhJfVjFfNnft\
J2kNBnASzMjDjVjSjSjFjOjUiTjDjBjMjFjIQXhJfVjGfOnftJ2kPBnAEXzOjTjFjUiWjBjMjVjFiBjU\
iUjJjNjFjJfVjFfNRCVjDfLVjHfPffJ2kQBnAEXjJfVjFfNRCVjEfMVjHfPffJ2kSBnAEXjJfVjGfORC\
VjDfLVjIfQffJ2kTBnAEXjJfVjGfORCVjEfMVjIfQffAVidfCnAChWXLfVTfBnndAb2kXBn0ADJ2kXBn\
ASgaJEXgbfXgcfVMfARBXiZfVMfAffnftJ2kYBnABXhffVgafJXiafVMfAnfO2kbBb2kcBn0AKJ2kcBn\
ASjDLXhffVgafJnftJ2kdBnASjEMXiBfVgafJnftJ2kfBnASjFNEXgffEXgffVgafJRBFeJiUjSjBjOj\
TjGjPjSjNffRBFeIiQjPjTjJjUjJjPjOffnftJ2lABnASjGOEXgffEXgffVgafJRBFeJiUjSjBjOjTjG\
jPjSjNffRBFeFiTjDjBjMjFffnftJ2lCBnASzDjQjPjTjKRXhJfVjFfNnftJ2lDBnASzFjTjDjBjMjFj\
LSXhJfVjGfOnftJ2lFBnAEXjJfVjFfNRCVjDfLVjKfRffJ2lGBnAEXjJfVjFfNRCVjEfMVjKfRffJ2lI\
BnAEXjJfVjGfORCVjDfLVjLfSffJ2lJBnAEXjJfVjGfORCVjEfMVjLfSffAVidfCnJ2lNBnAEXibfjPf\
nfATV4G0AiAT4B0AiAiA4K0AiAjK4R0AiAM40BiAjH4P0AiAX4H0AiAga4J0AiAid4C0AiAie4D0AiAi\
f4E0AiAjA4F0AiAjB4I0AiAjD4L0AiAjE4M0AiAjF4N0AiAjG4O0AiAjI4Q0AiAjL4S0AiAATAzKjDjS\
jFjBjUjFiOjVjMjMjMA2lOBM2lSBbyBn0ABg2lUBbyBn0AOJ2lVBnASMAXNfXOfjPfnftO2lWBby2lXB\
n0ABf2lXBnAEjzFiFjSjSjPjSjNfRBFegciOjPhAjBjDjUjJjWjFhAjDjPjNjQjPjTjJjUjJjPjOhAjG\
jPjVjOjEhOftAUIhJVMfAhJCRVMfAjSfnnnnnJ2laBnAShZBXTfVMfAnftJ2lbBnAShaCXLfVhZfBnft\
J2ldBnASzFjDjPjMjPjSjODARDFdAFdAFdAfnftO2mABb2mBBn0ACJ2mBBnASzLjQjJjDjLjFjEiDjPj\
MjPjSjPEEjhSfRBARDFdBFdBFdBfffnftO2mCBby2mDBn0ABJ2mDBnASjODVjPfEnffACzDhBhdhdjQV\
jPfEnnbnAXiTfXiUfXiVfjiWfnJ2mIBnAEXhYfjPfRBFePiOjFjXhAiTjPjMjJjEhAiMjBjZjFjSffJ2\
mKBnASzCjUhRjRFEXzFjSjPjVjOjEjSfjzEiNjBjUjIjTfRBCzBhKjUXhOfVjOfDnndnfffnftJ2mLBn\
ASzCjUhSjVGEXjSfjjTfRBCjUXhPfVjOfDnndnfffnftJ2mMBnASzCjUhTjWHEXjSfjjTfRBCjUXhQfV\
jOfDnndnfffnftJ2mNBnASzEjUjFjYjUjXICiNCiNCiNCiNCiNCiNnVjRfFeBibnnneBhMVjVfGnnnne\
BhMVjWfHnnnneBidnftJ2mOBnASzIjMjBjZjFjSiTjUjSjYJdUzChGhGjZCjQEXhRfVjOfDnfnneFhQh\
MhQhMhQCjQEXhRfVjOfDnfnneHhRhMhRhMhRhMhRnnCiNnVjXfIeGiTjPjMjJjEhAnFeLiTjPjMjJjEh\
AiMjBjZjFjSnftO2mRBb2mSBn0AGJ2mSBnASzNjTjFjMjFjDjUjFjEiMjBjZjFjSjaLXhOfVhZfBnftO\
2mTBby2mUBn0ABf2mUBnAEjjNfRBFehCiTjFjMjFjDjUjFjEhAjMjBjZjFjShAjJjThAjJjOjWjBjMjJ\
jEhAjPjShAjOjVjMjMhOftAUIhJVjafLCGVjafLnnbnnnJ2mWBnASjBMCiYXiBfVjafLXhffVjafLnnn\
ftJ2mYBnASzJjOjFjXiTjPjMjJjEhSjbKEXiMfXgcfVMfARGEXzGjTjQjMjJjDjFjcfVjOfDRCFdAFdD\
ffVjYfJXiOfVMfAXiPfVMfAFdBVjBfMffnftJ2nABnAEXiSfVjbfKRBVjafLffJ2nBBnABXhffVjbfKX\
hffVjafLnfAChWVhafCnndAb2nDBn0ACJ2nDBnASjbKEXiMfXgcfVMfARGEXjcfVjOfDRCFdAFdDffVj\
YfJXiOfVMfAXiPfVMfAFdBXiZfVMfAffnftJ2nLBnABXhffVjbfKXiafVMfAnfJ2nNBnAEXibfjPfnfA\
BnzBjFjdnnANjP4E0AiAha4C0AiAjR4F0AiAjV4G0AiAjW4H0AiAjY4J0AiAjb4K0AiAja4L0AiAM40B\
iAjO4D0AiAjX4I0AiAjB4M0AiAhZ4B0AiAANAzLjDjSjFjBjUjFiTjPjMjJjEjeA2nQBM2nTBbyBn0AE\
J2nUBnAEXhYfjPfRBFeOiOjFjXhAiUjFjYjUhAiMjBjZjFjSffJ2nVBnASMAXNfXOfjPfnftO2nWBb2n\
YBn0AFJ2nYBnASjaBXhOfXTfVMfAnftJ2nZBnASzHjOjFjXiUjFjYjUjfCEXzHjBjEjEiUjFjYjUkAfX\
gcfVMfAnfnftJ2naBnABXhffVjffCXhffVjafBnfJ2nbBnABXiBfVjffCXiBfVjafBnfJ2ndBnAEXiSf\
VjffCRBVjafBffAChWXLfXTfVMfAnndAb2CCn0ACJ2CCnASjfCEXkAfXgcfVMfAnfnftJ2DCnABXhffV\
jffCXiafVMfAnfJ2HCnAEXibfjPfnfADja4B0AiAjf4C0AiAM40BiAADAzKjDjSjFjBjUjFiUjFjYjUk\
BA2ICM2KCbyBn0AGJ2LCnAEXhYfjPfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJ2NCnASMAXNfX\
OfjPfnftJ2OCnASjaBXhOfXTfVMfAnftJ2PCnASzDjGjQjTkCCXzJjGjSjBjNjFiSjBjUjFkDfVMfAnf\
tK2RCb2SCn0AEJ2SCnASiXEEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfF\
d8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiOfVMfAXiPfVMfAFdBCzBhPkE\
nXkDfVMfAdBnffnftJ2TCnABXiQfViXfEnctfJ2UCnAEXiSfViXfERBVjafBffJ2WCnABXhffViXfECi\
NXhffVjafBCjUVVfDXzNjGjSjBjNjFiEjVjSjBjUjJjPjOkFfVMfAnnnnnfASVDVzBjYkGfFnftChWVV\
fDnndyBTVDyBtJ2YCnAEXibfjPfnfAGV4D0AiAkG40BhAja4B0AiAkC4C0AiAM40BiAiX4E0AiABFAzQ\
jDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiMkHA2ZCM2gbCbyBn0AGJ2gcCnAEXhYfjPfRBFePiOjFjXhAiP\
jOjFhAiGjSjBjNjFjSjTffJ2geCnASMAXNfXOfjPfnftJ2gfCnASjaBXhOfXTfVMfAnftJ2hACnASkCC\
XkDfVMfAnfta2hCCb2hDCn0AEJ2hDCnASiXEEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZmJhfFd8kakZ\
kZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiOfVMfAXiPfV\
MfAFdBCkEnXkDfVMfAdBnffnftJ2hECnABXiQfViXfEnctfJ2hFCnAEXiSfViXfERBVjafBffJ2hHCnA\
BXhffViXfECiYXiBfVjafBCjUVVfDXkFfVMfAnnnnnfAVVfDBVkGfFByBhMJ2hJCnAEXibfjPfnfAGV4\
D0AiAkG40BhAja4B0AiAkC4C0AiAM40BiAiX4E0AiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiSk\
IA2hKCM2hMCbyBn0AFJ2hOCnASMAXNfXOfjPfnftJ2hPCnASjaBXhOfXTfVMfAnftJ2hSCnASzFjDjPj\
VjOjUkJDQhLfjBfjCfnftK2hUCb2hXCn0AHJ2hXCnASiXCEXiMfXgcfVMfARGARDFd8kakZkZkZkZkZm\
JhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiO\
fVMfAXiPfVMfAFdBCjUXkFfVMfAnnd8kFnLiRlYgekFnPhfffnffJ2hYCnABXiQfViXfCnctfJ2hZCnA\
EXiSfViXfCRBVjafBffJ2hbCnABXWfViXfCncffJ2hcCnABjzBjZkKfCiNXzEjUjJjNjFkLfVMfACjUV\
kJfDXkFfVMfAnnnnnfJ2heCnABXhffViXfCjkKfnfJ2iBCnASkJDCiYnnndBntfASVEVkGfFnftChWVV\
fEnndyBTVEyBtJ2iFCnABXTfVMfAAnnfAGV4E0AiAkG40BhAja4B0AiAM40BiAkJ4D0AiAiX4C0AiABF\
AzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiNkMA2iGCM2iJCbyBn0AKJ2iKCnAEXhYfjPfRBFeViDjSjF\
jBjUjFhAiNjBjTjLhAjGjSjPjNhAiUjFjYjUffJ2iLCnASMAXNfXOfjPfnftJ2iMCnASzOjDjSjFjBjU\
jFiTjIjBjQjFjTiJiEkNBEXzRjGjJjOjEiNjFjOjViDjPjNjNjBjOjEiJjEkOfjPfRBFeXiDjSjFjBjU\
jFhAiTjIjBjQjFjThAjGjSjPjNhAiUjFjYjUffnftJ2iNCnAEXzMjPjQjFjOiJjOiWjJjFjXjFjSkPfV\
MfAnfJ2iOCnASzJjUjFjYjUiMjBjZjFjSkQCXhOfXTfVMfAnftJ2iPCnASzKjHjMjPjCjBjMiUjFjYjU\
kRDEXhRfXhJfEXgffVkQfCRBFeLiTjPjVjSjDjFhAiUjFjYjUffnfnftJ2iRCnAEXhHfjPfRBVkNfBff\
J2iTCnASzKjTjIjBjQjFiMjBjZjFjSkSEXhOfXTfVMfAnfta2iUCb2iVCn0AEa2iVCby2iWCn0ABO2iW\
Cby2iXCn0ABJ2iXCnABXhEfEXgffEXgffVkSfERBFeIiDjPjOjUjFjOjUjTffRBQhLfVkRfDViAfGffn\
cffACKViAfGVVfFnnby2ibCn0ABJ2ibCnABXhEfEXgffEXgffVkSfERBFeIiDjPjOjUjFjOjUjTffRBQ\
hLfVkRfDViAfGffnctfAViAfGAXLfVkRfDByBhMJ2ifCnASzDjEjVjQkTHEXzJjEjVjQjMjJjDjBjUjF\
kUfVkSfEnfnftJ2jACnABXiJfVkTfHQhLfVkRfDVVfFnfJ2jBCnAEXiSfVkTfHRBXhOfXTfVMfAffAVV\
fFAXLfVkRfDByBhMJ2jDCnAEXibfjPfnfAIV4F0AiAiA4G0AiAM40BiAkN4B0AiAkQ4C0AiAkR4D0AiA\
kS4E0AiAkT4H0AiAAIAzOjDjSjFjBjUjFiUjFjYjUiNjBjTjLkVA2jECM2jGCbyBn0AJJ2jICnASMAXN\
fXOfjPfnftJ2jJCnASkNBEXkOfjPfRBFeWiDjSjFjBjUjFhAiNjBjTjLjThAjGjSjPjNhAiUjFjYjUff\
nftJ2jKCnAEXkPfVMfAnfJ2jLCnASkQCXhOfXTfVMfAnftJ2jMCnASkRDEXhRfXhJfEXgffVkQfCRBFe\
LiTjPjVjSjDjFhAiUjFjYjUffnfnftJ2jNCnAEXhHfjPfRBVkNfBffJ2jPCnASkSEXhOfXTfVMfAnfta\
2jQCb2jRCn0AEa2jRCby2jSCn0ABO2jSCby2jTCn0ABJ2jTCnABXhEfEXgffEXgffVkSfERBFeIiDjPj\
OjUjFjOjUjTffRBQhLfVkRfDViAfGffncffACKViAfGVVfFnnby2jWCn0ABJ2jWCnABXhEfEXgffEXgf\
fVkSfERBFeIiDjPjOjUjFjOjUjTffRBQhLfVkRfDViAfGffnctfAViAfGAXLfVkRfDByBhMJ2jZCnASk\
THEXkUfVkSfEnfnftJ2jaCnABXiJfVkTfHQhLfVkRfDVVfFnfJ2jbCnAEXiSfVkTfHRBXhOfXTfVMfAf\
fAVVfFAXLfVkRfDByBhMJ2jdCnAEXhKfXhOfXTfVMfAnfAIV4F0AiAiA4G0AiAM40BiAkN4B0AiAkQ4C\
0AiAkR4D0AiAkS4E0AiAkT4H0AiAAIAzPjDjSjFjBjUjFiUjFjYjUiNjBjTjLhSkWA2jeCNJQnASzHjN\
jZiQjBjOjFjMkXAdCRVzHjUjIjJjTiPjCjKkYfRjzFiQjBjOjFjMkZfnnVkYfREjzGiXjJjOjEjPjXka\
fREFeHjQjBjMjFjUjUjFFeNjNjVjGjGjJjOhAjMjBjZjFjSjTjzJjVjOjEjFjGjJjOjFjEkbfWzGiPjC\
jKjFjDjUkcBzKjSjFjTjJjajFjBjCjMjFkdFctftnftJXnABXzNjBjMjJjHjOiDjIjJjMjEjSjFjOkef\
VkXfAARCFeEjMjFjGjUFeDjUjPjQfnfJYnABXzHjNjBjSjHjJjOjTkffVkXfAndFfJZnABXzHjTjQjBj\
DjJjOjHlAfVkXfAndEfJganABXkefVkXfAARCFeEjGjJjMjMFeEjGjJjMjMfnfJgbnABXzLjPjSjJjFj\
OjUjBjUjJjPjOlBfVkXfAneFjTjUjBjDjLfJhAnASzIjHjSjPjVjQiPjOjFlCBEXzDjBjEjElDfVkXfA\
RDFeFjHjSjPjVjQjkbfFeIjHjSjPjVjQiPjOjFffnftJhBnABXkefVlCfBARCFeEjGjJjMjMFeEjGjJj\
MjMfnfJhDnABXkffVlCfBndAfJhEnABXlAfVlCfBndDfOhFbhGn0AhDJhGnASzDjBjEjKlECEXlDfVlC\
fBRDFeGjCjVjUjUjPjOjkbfFeDiBiEiKffnftJhHnASzDjOjVjMlFDEXlDfVlCfBRDFeGjCjVjUjUjPj\
OjkbfFeEiOjVjMjMffnftJhInASjXEEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeEiUjFjYjUffnftJhJ\
nASzFjTjPjMjJjElGFEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeFiTjPjMjJjEffnftJhKnASzHiNjGj\
SjBjNjFjTlHGEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfFeB2kSBffnftJhLnASzIjEjSjPjQiEjPjXjOl\
IHEXlDfVlCfBRDFeMjEjSjPjQjEjPjXjOjMjJjTjUjkbfAREFdBFdCFdDFdEfffnftJhMnABXzJjTjFj\
MjFjDjUjJjPjOlJfVlIfHndCfJhOnASzGjSjFjOjBjNjFlKIEXlDfVlCfBRDFeGjCjVjUjUjPjOjkbfF\
eGjSjFjOjBjNjFffnftJhQnASzIjHjSjPjVjQiUjXjPlLJEXlDfVkXfARDFeFjHjSjPjVjQjkbfFeIjH\
jSjPjVjQiUjXjPffnftJhSnABXkefVlLfJARCFeEjGjJjMjMFeEjGjJjMjMfnfJhTnABXkffVlLfJndA\
fJhUnABXlAfVlLfJndDfJhWnABXiPfXzLjNjBjYjJjNjVjNiTjJjajFlMfVlLfJndZfJhYnASzEjBjEj\
KhSlNKEXlDfVlLfJRDFeGjCjVjUjUjPjOjkbfFeDiBiEiKffnftJhZnASzEjOjVjMhSlOLEXlDfVlLfJ\
RDFeGjCjVjUjUjPjOjkbfFeEiOjVjMjMffnftJhanASzFjUjFjYjUhSlPMEXlDfVlLfJRDFeGjCjVjUj\
UjPjOjkbfFeEiUjFjYjUffnftJhbnASzGjTjPjMjJjEhSlQNEXlDfVlLfJRDFeGjCjVjUjUjPjOjkbfF\
eFiTjPjMjJjEffnftJhcnASzIiNjGjSjBjNjFjThSlROEXlDfVlLfJRDFeGjCjVjUjUjPjOjkbfFeB2k\
SBffnftJhdnASzJjEjSjPjQiEjPjXjOhSlSPEXlDfVlLfJRDFeMjEjSjPjQjEjPjXjOjMjJjTjUjkbfA\
REFdBFdCFdDFdEfffnftJhenABXlJfVlSfPndCfJiAnASzHjSjFjOjBjNjFhSlTQEXlDfVlLfJRDFeGj\
CjVjUjUjPjOjkbfFeGjSjFjOjBjNjFffnftJiDnABXzIjPjOiDjIjBjOjHjFlUfVlIfHNyBnAMiDbyBn\
0ABJiEnABjCfXlJfjlIfnf0DhLCiFnfJiGnABXlUfVlSfPNyBnAMiGbyBn0ABJiHnABjCfXlJfjlSfnf\
0DhLCiInfJiKnABXzHjPjOiDjMjJjDjLlVfVlEfCNyBnAMiKbyBn0ACJiMnAEjicfRBjDfffJiNnABjD\
fCiNnnndBnt0DhLCiOnfJiQnABXlVfVlFfDNyBnAMiQbyBn0ABJiRnAEjjMfnf0DhLCiSnfJiUnABXlV\
fVlHfGNyBnAMiUbyBn0ABOiVbyiWn0ABJiWnAEjQfRBFeVjQjMjFjBjTjFhAjTjFjMjFjDjUhAjBhAjM\
jBjZjFjSffACGXLfXTfXNfXOfjPfnndAbiZn0ADJiZnAEXhYfjPfRBFePiOjFjXhAiPjOjFhAiGjSjBj\
NjFjSjTffJianAEjkMfRBQhLfjBfjCfffJibnAEXibfjPfnf0DhLCidnfJifnABXlVfVjXfENyBnAMif\
byBn0ABJjAnAEjkBfnf0DhLCjBnfJjDnABXlVfVlKfINyBnAMjDbyBn0ADJjEnAEXhYfjPfRBFeNiSjF\
jOjBjNjFhAiMjBjZjFjSjTffJjFnAEjzWjSjFjOjBjNjFiBjEjKjVjTjUjNjFjOjUiMjBjZjFjSjTlWf\
nfJjGnAEXibfjPfnf0DhLCjHnfJjInABXlVfVlTfQNyBnAMjIbyBn0ADJjJnAEXhYfjPfRBFeNiSjFjO\
jBjNjFhAiMjBjZjFjSjTffJjKnAEjlWfnfJjLnAEXibfjPfnf0DhLCjMnfJjPnABXlVfVlNfKNyBnAMj\
PbyBn0ACJjQnAEjicfRBjDfffJjRnABjDfCiNnnndBnt0DhLCjSnfJjUnABXlVfVlOfLNyBnAMjUbyBn\
0ABJjVnAEjjMfnf0DhLCjWnfJjYnABXlVfVlRfONyBnAMjYbyBn0ABOjZbyjan0ABJjanAEjQfRBFeVj\
QjMjFjBjTjFhAjTjFjMjFjDjUhAjBhAjMjBjZjFjSffACGXLfXTfXNfXOfjPfnndAbjen0ADJjenAEXh\
YfjPfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJkAnAEjkMfRBQhLfjBfjCfffJkBnAEXibfjPfn\
f0DhLCkEnfJkGnABXlVfVlPfMNyBnAMkGbyBn0ABJkHnAEjkBfnf0DhLCkInfJkKnABXlVfVlGfFNyBn\
AMkKbyBn0ABgkLbyBn0ABJkNnAEjjefnfABnjdnbyBn0ABJkQnAEjQfRBCiNCiNCiNCiNCiNnEXhRfjj\
dfnfeYiFjSjSjPjShAjJjOhAjTjPjMjJjEhOjPjOiDjMjJjDjLhaKnnneHKiMjJjOjFhahAXzEjMjJjO\
jFlXfjzBhElYfnnnneIKiTjUjBjDjLhahAXzFjTjUjBjDjLlZfjlYfnnff0DhLCkUnfJkWnABXlVfVlQ\
fNNyBnAMkWbyBn0ABgkXbyBn0ABJkZnAEjjefnfABnjdnbyBn0ABJkcnAEjQfRBCiNCiNCiNCiNCiNnE\
XhRfjjdfnfeZiFjSjSjPjShAjJjOhAjTjPjMjJjEhShOjPjOiDjMjJjDjLhaKnnneHKiMjJjOjFhahAX\
lXfjlYfnnnneIKiTjUjBjDjLhahAXlZfjlYfnnff0DhLClAnfACGjFfnneZjEjFjWjFjMjPjQjFjEhAj\
CjZhAjNjVjGjGjJjOjNjJjYhAhahTnJlEnABXzKjPjOiSjFjTjJjajJjOjHlafVkXfABXzIjPjOiSjFj\
TjJjajFlbfVkXfANyBnAMlEbyBn0AEJlGnABXlBfjlCfdChWXiOfXzEjTjJjajFlcfjkXfXiPfXlcfjk\
XfnnFeDjSjPjXFeGjDjPjMjVjNjOnfJlInABXlBfjlLfdChWXiOfXlcfjkXfXiPfXlcfjkXfnnFeDjSj\
PjXFeGjDjPjMjVjNjOnfOlKblMn0ACJlMnABXzHjWjJjTjJjCjMjFldfjlLfncffJlOnABXldfjlCfnc\
tfAUjZChWXiOfXlcfjkXfnndZChMXiOfXlcfjkXfXiPfXlcfjkXfnnnnblSn0ACJlSnABXldfjlCfncf\
fJlUnABXldfjlLfnctfJlYnAEXzGjSjFjTjJjajFlefXzGjMjBjZjPjVjUlffjkXfnf0DhLClanfnfOl\
cblen0ACJlenAEXzGjDjFjOjUjFjSmAfVkXfAnfJmAnAEXzEjTjIjPjXmBfVkXfAnfACRVkXfAjkafnn\
bmEn0ACJmEnAEXlffXlffVkXfARBFctffJmGnAEXlefXlffVkXfAnfASjX4E0AiAlK4I0AiAlP4M0AiA\
kX40BiAlC4B0AiAlE4C0AiAlF4D0AiAlG4F0AiAkY40BhAlH4G0AiAlI4H0AiAlL4J0AiAlN4K0AiAlO\
4L0AiAlQ4N0AiAlR4O0AiAlS4P0AiAlT4Q0AiABRAzIjCjVjJjMjEifiViJmCA2jfCM2kBCbyBn0ACa2\
kCCby2kDCn0ABO2kDCby2kECn0ABZ2kECnAFctACzDhdhdhdmDQhLfVhUfCVVfAVhJfBnnnAVVf0AXLf\
VhUfCByBhMZ2kHCnAFcfADV40BiAhJ40BhAhU4B0AhACBAzJjJjTiJjOiBjSjSjBjZmEA2kICM2kKCby\
Bn0AIJ2kLCnASMAXNfXOfjPfnftO2kMCb2kNCn0ACJ2kNCnAEjQfRBFegciQjMjFjBjTjFhAjTjFjMjF\
jDjUhAjBhAjDjPjNjQjPjTjJjUjJjPjOhOffZ2kOCnAnAUIhJVMfAhJCRVMfAjSfnnnnnO2kRCnAUICm\
DizGjUjZjQjFjPjGmFjzJjOjJjDjLjOjBjNjFjTmGfnneJjVjOjEjFjGjJjOjFjECGjmGfnnbnnnJy2k\
RCnABjmGfWkcAnfO2kSCnAUICmDimFjzKjFjYjDjMjVjTjJjPjOjTmHfnneJjVjOjEjFjGjJjOjFjECG\
jmHfnnbnnnJy2kSCnABjmHfAnnfJ2kUCnASgcBXgcfVMfAnfta2kVCb2kWCn0ACJ2kWCnASXDQhLfVgc\
fBVVfCnftO2kXCb2kYCn0ACJ2kYCnASzHjFjGjGjFjDjUjTmIEEXgffVXfDRBFeSiBiEiCiFhAiFjGjG\
jFjDjUhAiQjBjSjBjEjFffnftO2kZCb2kaCn0ADJ2kaCnASzHjOjFjXiOjBjNjFmJFneAfta2kbCb2kc\
Cn0ADJ2kcCnASzGjFjGjGjFjDjUmKHEXgffVmIfERBViAfGffnftJ2kdCnASzKjFjGjGjFjDjUiOjBjN\
jFmLIXiJfVmKfHnftO2kfCb2lACn0ACJ2lACnASzEjOjJjDjLmMJUIQhLfjmGfVmLfIVmLfInnnftJ2l\
BCnASmJFCiNnCiNVmMfJnneBhAnnntfAhJEjmEfRCVmLfIjmHfffnAViAfGBXzNjOjVjNiQjSjPjQjFj\
SjUjJjFjTmNfVmIfEByBZO2lECby2lFCn0ABJ2lFCnABXiJfVXfDVmJfFnfACjQVmJfFnneAnAChWXmN\
fVmIfEnndAnAUjZCRVXfDjzHiBiWiMjBjZjFjSmOfnnXiQfVXfDnnnAVVfCBXLfVgcfBByBZAKV4C0Ai\
AiA4G0AiAM40BiAmJ4F0AiAX4D0AiAgc4B0AiAmI4E0AiAmK4H0AiAmL4I0AiAmM4J0AiAAKAlWA2lKC\
M2lNCbyBn0ACJ2lOCnASMAXNfXOfjPfnftO2lPCb2lQCn0ACJ2lQCnAEjQfRBFegeiQjMjFjBjTjFhAj\
TjFjMjFjDjUhAjBjUhAjMjFjBjTjUhAhRhAjMjBjZjFjSffZ2lRCnAFcfACGXLfXTfVMfAnndAb2lTCn\
0ACJ2lTCnASgcBXTfVMfAnfta2lUCb2lVCn0AGJ2lVCnAEXhHfjPfRBEXkOfjPfRBFehEiDjFjOjUjFj\
ShAiBjOjDjIjPjShAiQjPjJjOjUhAjJjOhAiMjBjZjFjShAiDjPjOjUjFjOjUffffJ2lWCnAEXhFfEXg\
ffQhLfVgcfBVVfCRBFeIiQjPjTjJjUjJjPjOffRBARCCkEXiOfXNfXOfjPfnndCCkEXiPfXNfXOfjPfn\
ndCfffJ2lXCnAEXhFfEXgffQhLfVgcfBVVfCRBFeFiTjDjBjMjFffRBARCFdjEFdjEfffJ2lYCnAEXhF\
fEXgffQhLfVgcfBVVfCRBFeHiPjQjBjDjJjUjZffRBFdjEffJ2laCnAEXhFfEXgffQhLfVgcfBVVfCRB\
FeIiSjPjUjBjUjJjPjOffRBFdAffO2lcCby2ldCn0ABJ2ldCnAEXhFfEXgffQhLfVgcfBVVfCRBFeMiB\
jVjEjJjPhAiMjFjWjFjMjTffRBARCFdAFdAfffACKEXgffQhLfVgcfBVVfCRBFeMiBjVjEjJjPhAiMjF\
jWjFjMjTffnnbnAVVfCAXLfVgcfBByBhMADV4C0AiAM40BiAgc4B0AiAADAzOjSjFjTjFjUiUjSjBjOj\
TjGjPjSjNmPA2mBCBJ2mECnAEjmCfRBVkYfAffABkY40BhAB0AhLC2mGCRBezEjUjIjJjTmQfffAFB40\
BiAC4B0AiAD4C0AiAE4D0AiAF4E0AiAAFAhLByB");
